INSERT INTO hospitals (id, name, address, latitude, longitude, phone, emergency_available, status, capabilities, is_verified, last_verified_at, source_url, source_label) VALUES
('h-nimhans', 'NIMHANS Emergency Services', 'Hosur Road, Bengaluru, Karnataka 560029', 12.9438, 77.5964, '08026995000', TRUE, 'TRUSTED_RESOURCE', 'NEUROLOGICAL,MEDICAL_EMERGENCY,GENERAL', TRUE, '2026-09-19 12:00:00', 'https://www.nimhans.ac.in/emergency-services', 'NIMHANS official site'),
('h-apollo-bannerghatta', 'Apollo Hospitals Bannerghatta Road', '154/11, Bannerghatta Road, Bengaluru, Karnataka 560076', 12.8974, 77.5997, '18605001066', TRUE, 'TRUSTED_RESOURCE', 'CARDIO_RESPIRATORY,TRAUMA,MEDICAL_EMERGENCY,GENERAL', TRUE, '2026-09-19 12:00:00', 'https://www.apollohospitals.com/contact-us', 'Apollo official contact page (Lifeline)'),
('h-fortis-bg', 'Fortis Hospital Bannerghatta Road', '154/9, Bannerghatta Road, Bengaluru, Karnataka 560076', 12.8962, 77.6009, '9686096860', TRUE, 'TRUSTED_RESOURCE', 'CARDIO_RESPIRATORY,TRAUMA,MEDICAL_EMERGENCY,GENERAL', TRUE, '2026-09-19 12:00:00', 'https://www.fortishealthcare.com/lp/emergency-ambulance-number-bangalore', 'Fortis official emergency page'),
('h-aiims-delhi', 'AIIMS New Delhi Emergency', 'Ansari Nagar, New Delhi 110029', 28.5672, 77.2100, '26594405', TRUE, 'TRUSTED_RESOURCE', 'CARDIO_RESPIRATORY,NEUROLOGICAL,TRAUMA,MEDICAL_EMERGENCY', TRUE, '2026-09-19 12:00:00', 'https://www.aiims.edu/index.php/en/citizen-charter?id=231', 'AIIMS official citizen charter')
ON DUPLICATE KEY UPDATE name = VALUES(name), last_verified_at = VALUES(last_verified_at);

INSERT INTO doctors (id, name, phone, phone_label, specialty, hospital_id, is_on_call, is_verified, last_verified_at, source_url, source_label) VALUES
('d-nimhans-emergency', 'NIMHANS emergency clinician on-call', '08026995802', 'Official emergency services contact', 'Neurology / emergency services', 'h-nimhans', TRUE, TRUE, '2026-09-19 12:00:00', 'https://www.nimhans.ac.in/contact-us', 'NIMHANS official contact page'),
('d-aiims-neurosurgery', 'AIIMS neurosurgery resident on-call', '8929936770', 'Official neurosurgery resident on-call number', 'Neurosurgery', 'h-aiims-delhi', TRUE, TRUE, '2026-09-19 12:00:00', 'https://www.aiims.edu/index.php/en/citizen-charter?id=231', 'AIIMS official citizen charter'),
('d-apollo-lifeline', 'Apollo emergency clinician desk', '18605001066', 'Apollo Lifeline; ask for emergency clinician', 'Emergency medicine / cardiopulmonary care', 'h-apollo-bannerghatta', TRUE, TRUE, '2026-09-19 12:00:00', 'https://www.apollohospitals.com/contact-us', 'Apollo official contact page')
ON DUPLICATE KEY UPDATE name = VALUES(name), last_verified_at = VALUES(last_verified_at);
