import type { Doctor, Hospital } from "../../shared/carebridge";

const verifiedOn = "2026-09-19T12:00:00.000Z";

export const HOSPITALS: Hospital[] = [
  {
    id: "h-nimhans",
    name: "NIMHANS Emergency Services",
    address: "Hosur Road, Bengaluru, Karnataka 560029",
    latitude: 12.9438,
    longitude: 77.5964,
    phone: "08026995000",
    emergencyAvailable: true,
    status: "TRUSTED_RESOURCE",
    capabilities: ["NEUROLOGICAL", "MEDICAL_EMERGENCY", "GENERAL"],
    isVerified: true,
    lastVerifiedAt: verifiedOn,
    sourceUrl: "https://www.nimhans.ac.in/emergency-services",
    sourceLabel: "NIMHANS official site",
  },
  {
    id: "h-apollo-bannerghatta",
    name: "Apollo Hospitals Bannerghatta Road",
    address: "154/11, Bannerghatta Road, Bengaluru, Karnataka 560076",
    latitude: 12.8974,
    longitude: 77.5997,
    phone: "18605001066",
    emergencyAvailable: true,
    status: "TRUSTED_RESOURCE",
    capabilities: ["CARDIO_RESPIRATORY", "TRAUMA", "MEDICAL_EMERGENCY", "GENERAL"],
    isVerified: true,
    lastVerifiedAt: verifiedOn,
    sourceUrl: "https://www.apollohospitals.com/contact-us",
    sourceLabel: "Apollo official contact page (Lifeline)",
  },
  {
    id: "h-fortis-bg",
    name: "Fortis Hospital Bannerghatta Road",
    address: "154/9, Bannerghatta Road, Bengaluru, Karnataka 560076",
    latitude: 12.8962,
    longitude: 77.6009,
    phone: "9686096860",
    emergencyAvailable: true,
    status: "TRUSTED_RESOURCE",
    capabilities: ["CARDIO_RESPIRATORY", "TRAUMA", "MEDICAL_EMERGENCY", "GENERAL"],
    isVerified: true,
    lastVerifiedAt: verifiedOn,
    sourceUrl: "https://www.fortishealthcare.com/lp/emergency-ambulance-number-bangalore",
    sourceLabel: "Fortis official emergency page",
  },
  {
    id: "h-aiims-delhi",
    name: "AIIMS New Delhi Emergency",
    address: "Ansari Nagar, New Delhi 110029",
    latitude: 28.5672,
    longitude: 77.2100,
    phone: "26594405",
    emergencyAvailable: true,
    status: "TRUSTED_RESOURCE",
    capabilities: ["CARDIO_RESPIRATORY", "NEUROLOGICAL", "TRAUMA", "MEDICAL_EMERGENCY"],
    isVerified: true,
    lastVerifiedAt: verifiedOn,
    sourceUrl: "https://www.aiims.edu/index.php/en/citizen-charter?id=231",
    sourceLabel: "AIIMS official citizen charter",
  },
];

export const DOCTORS: Doctor[] = [
  {
    id: "d-nimhans-emergency",
    name: "NIMHANS emergency clinician on-call",
    phone: "08026995802",
    phoneLabel: "Official emergency services contact",
    specialty: "Neurology / emergency services",
    hospitalId: "h-nimhans",
    isOnCall: true,
    isVerified: true,
    lastVerifiedAt: verifiedOn,
    sourceUrl: "https://www.nimhans.ac.in/contact-us",
    sourceLabel: "NIMHANS official contact page",
  },
  {
    id: "d-aiims-neurosurgery",
    name: "AIIMS neurosurgery resident on-call",
    phone: "8929936770",
    phoneLabel: "Official neurosurgery resident on-call number",
    specialty: "Neurosurgery",
    hospitalId: "h-aiims-delhi",
    isOnCall: true,
    isVerified: true,
    lastVerifiedAt: verifiedOn,
    sourceUrl: "https://www.aiims.edu/index.php/en/citizen-charter?id=231",
    sourceLabel: "AIIMS official citizen charter",
  },
  {
    id: "d-apollo-lifeline",
    name: "Apollo emergency clinician desk",
    phone: "18605001066",
    phoneLabel: "Apollo Lifeline; ask for emergency clinician",
    specialty: "Emergency medicine / cardiopulmonary care",
    hospitalId: "h-apollo-bannerghatta",
    isOnCall: true,
    isVerified: true,
    lastVerifiedAt: verifiedOn,
    sourceUrl: "https://www.apollohospitals.com/contact-us",
    sourceLabel: "Apollo official contact page",
  },
];
